// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionControl.Infrastructure.Data;

#nullable disable

namespace MissionControl.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MissionControl.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Message = "🌀 Whis initialized — autonomous orchestration active",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            Message = "😼 Beerus completed architecture design for agent communication",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 3,
                            Message = "🔥 Kakarot started coding OrchestratorService",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 7,
                            Message = "💾 Trunks stored architecture decision to long-term memory",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 5,
                            Message = "🌿 Piccolo refactored memory system to structured summaries",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AgentId = 6,
                            Message = "📖 Gohan reviewing memory refactor — checking structured output",
                            ProjectId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionBackend")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenClawAgentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PushRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToolsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Orchestrator — routes tasks, manages state machine, handles retries",
                            Emoji = "🌀",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "llama3",
                            Name = "Whis",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 0,
                            Skills = "Orchestration,Routing,Escalation",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "Architect — high-level system design and decisions",
                            Emoji = "😼",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "qwen2.5-coder:14b-instruct-q4_K_M",
                            Name = "Beerus",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 1,
                            Skills = "Architecture,SystemDesign,Planning",
                            Status = 0,
                            ToolsEnabled = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Standard coder for moderate complexity tasks",
                            Emoji = "🔥",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "llama3",
                            Name = "Kakarot",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 2,
                            Skills = "Coding,Implementation,Testing",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            Description = "Advanced coder — handles high complexity and critical tasks",
                            Emoji = "⚡",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "qwen2.5-coder:14b-instruct-q4_K_M",
                            Name = "Vegeta",
                            ProjectId = 1,
                            PushRole = true,
                            Role = 3,
                            Skills = "AdvancedCoding,Performance,Security",
                            Status = 0,
                            ToolsEnabled = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "Refactorer — cleans code, applies SOLID principles",
                            Emoji = "🌿",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "llama3",
                            Name = "Piccolo",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 4,
                            Skills = "Refactoring,CleanCode,SOLID",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 6,
                            Description = "Reviewer — inspects output, approves or triggers fix cycle",
                            Emoji = "📖",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "qwen2.5-coder:14b-instruct-q4_K_M",
                            Name = "Gohan",
                            ProjectId = 1,
                            PushRole = true,
                            Role = 5,
                            Skills = "CodeReview,QualityAssurance,Security",
                            Status = 0,
                            ToolsEnabled = true
                        },
                        new
                        {
                            Id = 7,
                            Description = "Memory & learning — stores summaries, refines routing weights",
                            Emoji = "💾",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "llama3",
                            Name = "Trunks",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 6,
                            Skills = "MemoryManagement,Learning,Analytics",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tooling — manages context injection and prompt construction",
                            Emoji = "🔧",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "qwen2.5-coder:14b-instruct-q4_K_M",
                            Name = "Bulma",
                            ProjectId = 1,
                            PushRole = true,
                            Role = 7,
                            Skills = "Tooling,ContextManagement,PromptEngineering",
                            Status = 0,
                            ToolsEnabled = true
                        },
                        new
                        {
                            Id = 9,
                            Description = "Security Auditor — static/dynamic analysis, vulnerability checks",
                            Emoji = "🦗",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o-mini",
                            Name = "Cell",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 8,
                            Skills = "Security,Audit,Analysis",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 10,
                            Description = "Test Engineer — automated/unit/integration/fuzz testing",
                            Emoji = "🧑‍🦲",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o-mini",
                            Name = "Dende",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 9,
                            Skills = "Testing,QA,Fuzzing",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 11,
                            Description = "Release Manager — deployment, monitoring, rollback",
                            Emoji = "🐉",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o-mini",
                            Name = "Shenron",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 10,
                            Skills = "Release,Deployment,Monitoring",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 12,
                            Description = "Compliance/Legal — licensing, privacy, regulatory checks",
                            Emoji = "👽",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o-mini",
                            Name = "Jaco",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 11,
                            Skills = "Compliance,Legal,Privacy",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 13,
                            Description = "Supreme Overseer — self-improvement, process optimization, ultimate authority",
                            Emoji = "👑",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o",
                            Name = "Zeno",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 12,
                            Skills = "Oversight,Optimization,Authority",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 14,
                            Description = "Enforcer — ultimate strength, handles escalations, last-resort interventions",
                            Emoji = "💪",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o",
                            Name = "Jiren",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 13,
                            Skills = "Enforcement,Escalation,Intervention",
                            Status = 0,
                            ToolsEnabled = false
                        },
                        new
                        {
                            Id = 15,
                            Description = "Grand Priest — father of Whis, supreme angel, oversees all angels and orchestrators",
                            Emoji = "🧙‍♂️",
                            ExecutionBackend = "OpenClaw",
                            IsPaused = false,
                            Model = "gpt-4o",
                            Name = "GrandPriest",
                            ProjectId = 1,
                            PushRole = false,
                            Role = 14,
                            Skills = "Oversight,Orchestration,Leadership",
                            Status = 0,
                            ToolsEnabled = false
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentName");

                    b.HasIndex("Level");

                    b.HasIndex("TaskId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.MemoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SuccessRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("MemoryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confidence = 0.5,
                            Content = "We will use strict state-machine driven execution. Only status transitions trigger agent actions. No polling loops.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRule = false,
                            ProjectId = 1,
                            SuccessRate = 0.5,
                            Tags = "architecture,state-machine,agents",
                            Title = "Architecture Decision: Event-Driven Agents",
                            Type = 2,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 7,
                            Confidence = 0.5,
                            Content = "Injecting .md files into every prompt increased token usage 3×. Switched to ContextLoader with caching. 70% reduction in token spend.",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRule = false,
                            ProjectId = 1,
                            SuccessRate = 0.5,
                            Tags = "performance,prompts,context",
                            Title = "Performance Insight: Prompt Bloat",
                            Type = 1,
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 7,
                            Confidence = 0.5,
                            Content = "Store only structured summaries: {task_id, problem, fix, lesson}. Never store raw conversation history.",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRule = false,
                            ProjectId = 1,
                            SuccessRate = 0.5,
                            Tags = "memory,summaries,structured",
                            Title = "Memory Refactor Decision",
                            Type = 2,
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.MemorySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lesson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetriesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MemorySummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentRole = "Beerus",
                            ComplexityScore = 9,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fix = "Implemented SignalR hub with typed methods per event type",
                            Lesson = "Event-driven beats polling — always push, never pull",
                            Problem = "Agent communication was polling-based and inefficient",
                            ProjectId = 1,
                            RetriesRequired = 0,
                            TaskItemId = 1
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The primary autonomous AI engineering lab",
                            Name = "Alpha Project"
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StatusEnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAgentId = 2,
                            ComplexityScore = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architect the event-driven messaging layer between agents",
                            Priority = 3,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 15,
                            Title = "Design autonomous agent communication protocol",
                            UpdatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssignedAgentId = 3,
                            ComplexityScore = 8,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "State-machine driven task routing and agent assignment",
                            Priority = 3,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 5,
                            Title = "Implement OrchestratorService (Whis)"
                        },
                        new
                        {
                            Id = 3,
                            AssignedAgentId = 5,
                            ComplexityScore = 5,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Remove full conversation storage, use JSON summaries only",
                            Priority = 2,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 9,
                            Title = "Refactor memory to structured summaries"
                        },
                        new
                        {
                            Id = 4,
                            ComplexityScore = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SignalR-connected live agent activity feed",
                            Priority = 2,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 0,
                            Title = "Build Angular dashboard real-time feed"
                        },
                        new
                        {
                            Id = 5,
                            AssignedAgentId = 8,
                            ComplexityScore = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cache SOUL and AGENTS context to avoid prompt bloat",
                            Priority = 1,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 4,
                            Title = "Add context caching to ContextLoader"
                        },
                        new
                        {
                            Id = 6,
                            ComplexityScore = 7,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Analyze past summaries and refine routing weights",
                            Priority = 1,
                            ProjectId = 1,
                            RetryCount = 0,
                            ReviewFailCount = 0,
                            Status = 3,
                            Title = "Implement learning service (Trunks)"
                        });
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Agent", "Agent")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Agent", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("Agents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissionControl.Domain.Entities.Team", "Team")
                        .WithMany("Agents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.MemoryEntry", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("MemoryEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.MemorySummary", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("MemorySummaries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Agent", "AssignedAgent")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MissionControl.Domain.Entities.TaskItem", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId");

                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Team", b =>
                {
                    b.HasOne("MissionControl.Domain.Entities.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Agent", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Project", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Agents");

                    b.Navigation("MemoryEntries");

                    b.Navigation("MemorySummaries");

                    b.Navigation("Tasks");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("MissionControl.Domain.Entities.Team", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
